<?php
$stations=[
    'Taiwan'=>[
        'EN'=>'台灣',
        'TW'=>'Taiwan',
        'airport'=>[
            [
                'code'=>'TSA',
                'EN'=>'TSA',
                'TW'=>'Taipei Songshan',
            ],[
                'code'=>'TPE',
                'EN'=>'TPE',
                'TW'=>'Taoyuan',
            ],[
                'code'=>'TPE',
                'EN'=>'TPE',
                'TW'=>'Taoyuan',
            ],[
                'code'=>'RMQ',
                'EN'=>'RMQ',
                'TW'=>'Taichung',
            ],[
                'code'=>'KHH',
                'EN'=>'KHH',
                'TW'=>'Kaohsiung',
            ],
        ],
    ],
    'Vietnam'=>[
        'EN'=>'Vietnam',
        'TW'=>'Vietnam',
        'airport'=>[
            [
                'code'=>'HAN',
                'EN'=>'HAN',
                'TW'=>'Thành phố Hà Nội',
            ],[
                'code'=>'SGN',
                'EN'=>'SGN',
                'TW'=>'Thành phố Hồ Chí Minh',
            ],[
                'code'=>'DAD',
                'EN'=>'DAD',
                'TW'=>'Thành phố Đà Nẵng',
            ],[
                'code'=>'PQC',
                'EN'=>'PQC',
                'TW'=>'Đảo Phú Quốc',
            ],[
                'code'=>'CXR',
                'EN'=>'CXR',
                'TW'=>'Thành phố Nha Trang',
            ],[
                'code'=>'DLI',
                'EN'=>'DLI',
                'TW'=>'Thành phố Đà Lạt',
            ],
        ],
    ],
    'Indonesia'=>[
        'EN'=>'Indonesia',
        'TW'=>'Indonesia',
        'airport'=>[
            [
                'code'=>'CGK',
                'EN'=>'CGK',
                'TW'=>'Jakarta',
            ],
            [
                'code'=>'YIA',
                'EN'=>'YIA',
                'TW'=>'Yogyakarta',
            ],
            [
                'code'=>'DPS',
                'EN'=>'DPS',
                'TW'=>'Denpasar',
            ],
            [
                'code'=>'SUB',
                'EN'=>'SUB',
                'TW'=>'Surabaya',
            ],
            [
                'code'=>'KNO',
                'EN'=>'KNO',
                'TW'=>'Medan',
            ],
            [
                'code'=>'LBJ',
                'EN'=>'LBJ',
                'TW'=>'Labuan Bajo',
            ],
            [
                'code'=>'BTH',
                'EN'=>'BTH',
                'TW'=>'Batam',
            ],
            [
                'code'=>'SRG',
                'EN'=>'SRG',
                'TW'=>'Semarang',
            ],
            [
                'code'=>'UPG',
                'EN'=>'UPG',
                'TW'=>'Makassar',
            ],
            [
                'code'=>'MLG',
                'EN'=>'MLG',
                'TW'=>'Kota Malang',
            ],
            [
                'code'=>'MDC',
                'EN'=>'MDC',
                'TW'=>'Manado',
            ],
            [
                'code'=>'PDG',
                'EN'=>'PDG',
                'TW'=>'Padang',
            ],
            [
                'code'=>'SOC',
                'EN'=>'SOC',
                'TW'=>'Surakarta',
            ],
            [
                'code'=>'PLM',
                'EN'=>'PLM',
                'TW'=>'Palembang',
            ],
            [
                'code'=>'BPN',
                'EN'=>'BPN',
                'TW'=>'Balikpapan',
            ],
            [
                'code'=>'AMQ',
                'EN'=>'AMQ',
                'TW'=>'Ambon',
            ],
            [
                'code'=>'PKU',
                'EN'=>'PKU',
                'TW'=>'Pekanbaru',
            ],
            [
                'code'=>'PNK',
                'EN'=>'PNK',
                'TW'=>'Pontianak',
            ],
            [
                'code'=>'BTJ',
                'EN'=>'BTJ',
                'TW'=>'Banda Aceh',
            ],
            [
                'code'=>'BDJ',
                'EN'=>'BDJ',
                'TW'=>'Banjarmasin',
            ],
            [
                'code'=>'TKG',
                'EN'=>'TKG',
                'TW'=>'Bandar Lampung',
            ],
            [
                'code'=>'DJJ',
                'EN'=>'DJJ',
                'TW'=>'Jayapura',
            ],
            [
                'code'=>'DJB',
                'EN'=>'DJB',
                'TW'=>'Jambi',
            ],
            [
                'code'=>'LOP',
                'EN'=>'LOP',
                'TW'=>'Lombok',
            ],
        ]
    ]
];