<?php
$stations=[
    'KeelungCity'=>[
        'TW'=>'基隆市',
        'EN'=>'Keelung City',
        'stations'=>[
            [
                'code'=>'0900',
                'TW'=>'基隆',
                'EN'=>'Keelung',
            ],
            [
                'code'=>'0910',
                'TW'=>'三坑',
                'EN'=>'Sankeng',
            ],
            [
                'code'=>'0920',
                'TW'=>'八堵',
                'EN'=>'Badu',
            ],
            [
                'code'=>'0930',
                'TW'=>'七堵',
                'EN'=>'Cidu',
            ],
            [
                'code'=>'0940',
                'TW'=>'百福',
                'EN'=>'Baifu',
            ],
            [
                'code'=>'7390',
                'TW'=>'暖暖',
                'EN'=>'Nuannuan',
            ],
            [
                'code'=>'7361',
                'TW'=>'海科館',
                'EN'=>'Haikeguan',
            ],
            [
                'code'=>'736',
                'TW'=>'八斗子',
                'EN'=>'Badouzi',
            ],
        ],
    ],
    'NewTaipeiCity'=>[
        'TW'=>'新北市',
        'EN'=>'New Taipei City',
        'stations'=>[

            [
                'code'=>'0950',
                'TW'=>'五堵',
                'EN'=>'Wudu',
            ],
            [
                'code'=>'0960',
                'TW'=>'汐止',
                'EN'=>'Sijhih',
            ],
            [
                'code'=>'0970',
                'TW'=>'汐科',
                'EN'=>'Xike',
            ],
            [
                'code'=>'1020',
                'TW'=>'板橋',
                'EN'=>'Banciao',
            ],
            [
                'code'=>'1030',
                'TW'=>'浮洲',
                'EN'=>'Fuzhou',
            ],
            [
                'code'=>'1040',
                'TW'=>'樹林',
                'EN'=>'Shulin',
            ],
            [
                'code'=>'1050',
                'TW'=>'南樹林',
                'EN'=>'South Shulin',
            ],
            [
                'code'=>'1060',
                'TW'=>'山佳',
                'EN'=>'Shanjia',
            ],
            [
                'code'=>'1070',
                'TW'=>'鶯歌',
                'EN'=>'Yingge',
            ],
            [
                'code'=>'7380',
                'TW'=>'四腳亭',
                'EN'=>'Sihjiaoting',
            ],
            [
                'code'=>'7360',
                'TW'=>'瑞芳',
                'EN'=>'Rueifang',
            ],
            [
                'code'=>'7350',
                'TW'=>'猴硐',
                'EN'=>'Houtung',
            ],
            [
                'code'=>'7330',
                'TW'=>'三貂嶺',
                'EN'=>'Sandiaoling',
            ],
            [
                'code'=>'7320',
                'TW'=>'牡丹',
                'EN'=>'Mudan',
            ],
            [
                'code'=>'7310',
                'TW'=>'雙溪',
                'EN'=>'Shuangsi',
            ],
            [
                'code'=>'7300',
                'TW'=>'貢寮',
                'EN'=>'Gungliao',
            ],
            [
                'code'=>'7290',
                'TW'=>'福隆',
                'EN'=>'Fulong',
            ],
            [
                'code'=>'7331',
                'TW'=>'大華',
                'EN'=>'Dahua',
            ],
            [
                'code'=>'7332',
                'TW'=>'十分',
                'EN'=>'Shihfen',
            ],
            [
                'code'=>'7333',
                'TW'=>'望古',
                'EN'=>'Wanggu',
            ],
            [
                'code'=>'7334',
                'TW'=>'嶺腳',
                'EN'=>'Lingjiao',
            ],
            [
                'code'=>'7335',
                'TW'=>'平溪',
                'EN'=>'Pingsi',
            ],
            [
                'code'=>'733',
                'TW'=>'菁桐',
                'EN'=>'Jingtong',
            ],


        ],
    ],
    'TaipeiCity'=>[
        'TW'=>'台北市',
        'EN'=>'Taipei City',
        'stations'=>[
            [
                'code'=>'0980',
                'TW'=>'南港',
                'EN'=>'Nangang',
            ],
            [
                'code'=>'0990',
                'TW'=>'松山',
                'EN'=>'Songshan',
            ],
            [
                'code'=>'1000',
                'TW'=>'臺北',
                'EN'=>'Taipei',
            ],
            [
                'code'=>'1010',
                'TW'=>'萬華',
                'EN'=>'Wanhua',
            ],

        ],
    ],
    'TaoyuanCity'=>[
        'TW'=>'桃園市',
        'EN'=>'Taoyuan City',
        'stations'=>[
            [
                'code'=>'1080',
                'TW'=>'桃園',
                'EN'=>'Taoyuan',
            ],
            [
                'code'=>'1090',
                'TW'=>'內壢',
                'EN'=>'Neili',
            ],
            [
                'code'=>'1100',
                'TW'=>'中壢',
                'EN'=>'Jhongli',
            ],
            [
                'code'=>'1110',
                'TW'=>'埔心',
                'EN'=>'Pusin',
            ],
            [
                'code'=>'1120',
                'TW'=>'楊梅',
                'EN'=>'Yangmei',
            ],
            [
                'code'=>'1130',
                'TW'=>'富岡',
                'EN'=>'Fugang',
            ],
            [
                'code'=>'114',
                'TW'=>'新富',
                'EN'=>'Xinfu',
            ],


        ],
    ],
    'HsinchuCity'=>[
        'TW'=>'新竹市',
        'EN'=>'Hsinchu City',
        'stations'=>[
            [
                'code'=>'1190',
                'TW'=>'北新竹',
                'EN'=>'North Hsinchu',
            ],

            [
                'code'=>'1210',
                'TW'=>'新竹',
                'EN'=>'Hsinchu',
            ],

            [
                'code'=>'1220',
                'TW'=>'三姓橋',
                'EN'=>'Sanxingqiao',
            ],

            [
                'code'=>'1230',
                'TW'=>'香山',
                'EN'=>'Siangshan',
            ],

            [
                'code'=>'1191',
                'TW'=>'千甲',
                'EN'=>'Qianjia',
            ],

            [
                'code'=>'119',
                'TW'=>'新莊',
                'EN'=>'Xinzhuang',
            ],
        ],
    ],
    'HsinchuCounty'=>[
        'TW'=>'新竹縣',
        'EN'=>'Hsinchu County',
        'stations'=>[
            [
                'code'=>'1150',
                'TW'=>'北湖',
                'EN'=>'Beihu',
            ],
            [
                'code'=>'1160',
                'TW'=>'湖口',
                'EN'=>'Hukou',
            ],
            [
                'code'=>'1170',
                'TW'=>'新豐',
                'EN'=>'Sinfong',
            ],
            [
                'code'=>'1180',
                'TW'=>'竹北',
                'EN'=>'Jhubei',
            ],
            [
                'code'=>'1193',
                'TW'=>'竹中',
                'EN'=>'Jhujhong',
            ],
            [
                'code'=>'1201',
                'TW'=>'上員',
                'EN'=>'Shangyuan',
            ],
            [
                'code'=>'1202',
                'TW'=>'榮華',
                'EN'=>'Ronghua',
            ],
            [
                'code'=>'1203',
                'TW'=>'竹東',
                'EN'=>'Jhudong',
            ],
            [
                'code'=>'1204',
                'TW'=>'橫山',
                'EN'=>'Hengshan',
            ],
            [
                'code'=>'1205',
                'TW'=>'九讚頭',
                'EN'=>'jiouzantou',
            ],
            [
                'code'=>'1206',
                'TW'=>'合興',
                'EN'=>'Hesing',
            ],
            [
                'code'=>'1207',
                'TW'=>'富貴',
                'EN'=>'Fuguei',
            ],
            [
                'code'=>'1208',
                'TW'=>'內灣',
                'EN'=>'Neiwan',
            ],
            [
                'code'=>'119',
                'TW'=>'六家',
                'EN'=>'Liujia',
            ],
        ],
    ],
    'MiaoliCounty'=>[
        'TW'=>'苗栗縣',
        'EN'=>'Miaoli County',
        'stations'=>[
            [
                'code'=>'1240',
                'TW'=>'崎頂',
                'EN'=>'Ciding',
            ],
            [
                'code'=>'1250',
                'TW'=>'竹南',
                'EN'=>'Jhunan',
            ],
            [
                'code'=>'3140',
                'TW'=>'造橋',
                'EN'=>'Zaociao',
            ],
            [
                'code'=>'3150',
                'TW'=>'豐富',
                'EN'=>'Fongfu',
            ],
            [
                'code'=>'3160',
                'TW'=>'苗栗',
                'EN'=>'Miaoli',
            ],
            [
                'code'=>'3170',
                'TW'=>'南勢',
                'EN'=>'Nanshih',
            ],
            [
                'code'=>'3180',
                'TW'=>'銅鑼',
                'EN'=>'Tongluo',
            ],
            [
                'code'=>'3190',
                'TW'=>'三義',
                'EN'=>'Sanyi',
            ],
            [
                'code'=>'2110',
                'TW'=>'談文',
                'EN'=>'Tanwan',
            ],
            [
                'code'=>'2120',
                'TW'=>'大山',
                'EN'=>'Dashan',
            ],
            [
                'code'=>'2130',
                'TW'=>'後龍',
                'EN'=>'Houlong',
            ],
            [
                'code'=>'2140',
                'TW'=>'龍港',
                'EN'=>'Longgang',
            ],
            [
                'code'=>'2150',
                'TW'=>'白沙屯',
                'EN'=>'Baishatun',
            ],
            [
                'code'=>'2160',
                'TW'=>'新埔',
                'EN'=>'Sinpu',
            ],
            [
                'code'=>'2170',
                'TW'=>'通霄',
                'EN'=>'Tongsiao',
            ],
            [
                'code'=>'218',
                'TW'=>'苑裡',
                'EN'=>'Yuanli',
            ],

        ],
    ],
    'TaichungCity'=>[
        'TW'=>'台中市',
        'EN'=>'Taichung City',
        'stations'=>[
            [
                'code'=>'3210',
                'TW'=>'泰安',
                'EN'=>'Taian',
            ],
            [
                'code'=>'3220',
                'TW'=>'后里',
                'EN'=>'Houli',
            ],
            [
                'code'=>'3230',
                'TW'=>'豐原',
                'EN'=>'Fongyuan',
            ],
            [
                'code'=>'3240',
                'TW'=>'栗林',
                'EN'=>'Lilin',
            ],
            [
                'code'=>'3250',
                'TW'=>'潭子',
                'EN'=>'Tanzih',
            ],
            [
                'code'=>'3260',
                'TW'=>'頭家厝',
                'EN'=>'Toujiacuo',
            ],
            [
                'code'=>'3270',
                'TW'=>'松竹',
                'EN'=>'Songzhu',
            ],
            [
                'code'=>'3280',
                'TW'=>'太原',
                'EN'=>'Taiyuan',
            ],
            [
                'code'=>'3290',
                'TW'=>'精武',
                'EN'=>'Jingwu',
            ],
            [
                'code'=>'3300',
                'TW'=>'臺中',
                'EN'=>'Taichung',
            ],
            [
                'code'=>'3310',
                'TW'=>'五權',
                'EN'=>'Wuquan',
            ],
            [
                'code'=>'3320',
                'TW'=>'大慶',
                'EN'=>'Dacing',
            ],
            [
                'code'=>'3330',
                'TW'=>'烏日',
                'EN'=>'Wuri',
            ],
            [
                'code'=>'3340',
                'TW'=>'新烏日',
                'EN'=>'Xinwuri',
            ],
            [
                'code'=>'3350',
                'TW'=>'成功',
                'EN'=>'Chenggong',
            ],
            [
                'code'=>'2190',
                'TW'=>'日南',
                'EN'=>'Rihnan',
            ],
            [
                'code'=>'2200',
                'TW'=>'大甲',
                'EN'=>'Dajia',
            ],
            [
                'code'=>'2210',
                'TW'=>'臺中港',
                'EN'=>'Taichung Port',
            ],
            [
                'code'=>'2220',
                'TW'=>'清水',
                'EN'=>'Cingshuei',
            ],
            [
                'code'=>'2230',
                'TW'=>'沙鹿',
                'EN'=>'Shalu',
            ],
            [
                'code'=>'2240',
                'TW'=>'龍井',
                'EN'=>'Longjing',
            ],
            [
                'code'=>'2250',
                'TW'=>'大肚',
                'EN'=>'Dadu',
            ],
            [
                'code'=>'2260',
                'TW'=>'追分',
                'EN'=>'Jhuifen',
            ],
        ],
    ],
    'NantouCounty'=>[
        'TW'=>'南投縣',
        'EN'=>'Nantou County',
        'stations'=>[
            [
                'code'=>'3432',
                'TW'=>'濁水',
                'EN'=>'Jhuoshuei',
            ],
            [
                'code'=>'3433',
                'TW'=>'龍泉',
                'EN'=>'Lungcyuan',
            ],
            [
                'code'=>'3434',
                'TW'=>'集集',
                'EN'=>'Jiji',
            ],
            [
                'code'=>'3435',
                'TW'=>'水里',
                'EN'=>'Shueili',
            ],
            [
                'code'=>'3436',
                'TW'=>'車埕',
                'EN'=>'Checheng',
            ],

        ],
    ],
    'ChanghuaCounty'=>[
        'TW'=>'彰化縣',
        'EN'=>'Changhua County',
        'stations'=>[
            [
                'code'=>'3360',
                'TW'=>'彰化',
                'EN'=>'Changhua',
            ],
            [
                'code'=>'3370',
                'TW'=>'花壇',
                'EN'=>'Huatan',
            ],
            [
                'code'=>'3380',
                'TW'=>'大村',
                'EN'=>'Datsun',
            ],
            [
                'code'=>'3390',
                'TW'=>'員林',
                'EN'=>'Yuanlin',
            ],
            [
                'code'=>'3400',
                'TW'=>'永靖',
                'EN'=>'Yongjing',
            ],
            [
                'code'=>'3410',
                'TW'=>'社頭',
                'EN'=>'Shetou',
            ],
            [
                'code'=>'3420',
                'TW'=>'田中',
                'EN'=>'Tianjhong',
            ],
            [
                'code'=>'3430',
                'TW'=>'二水',
                'EN'=>'Ershuei',
            ],
            [
                'code'=>'3431',
                'TW'=>'源泉',
                'EN'=>'Yuanciyuan',
            ],
        ]

    ],
    'YunlinCounty'=>[
        'TW'=>'雲林縣',
        'EN'=>'Yunlin County',
        'stations'=>[
            [
                'code'=>'3450',
                'TW'=>'林內',
                'EN'=>'Linnei',
            ],
            [
                'code'=>'3460',
                'TW'=>'石榴',
                'EN'=>'Shiliu',
            ],
            [
                'code'=>'3470',
                'TW'=>'斗六',
                'EN'=>'Douliu',
            ],
            [
                'code'=>'3480',
                'TW'=>'斗南',
                'EN'=>'Dounan',
            ],
            [
                'code'=>'3490',
                'TW'=>'石龜',
                'EN'=>'Shigui',
            ],

        ],
    ],
    'ChiayiCity'=>[
        'TW'=>'嘉義市',
        'EN'=>'Chiayi City',
        'stations'=>[
            [
                'code'=>'4070',
                'TW'=>'嘉北',
                'EN'=>'ChiaPei',
            ],[
                'code'=>'4080',
                'TW'=>'嘉義',
                'EN'=>'Chiayi',
            ],
        ],
    ],
    'ChiayiCounty'=>[
        'TW'=>'嘉義縣',
        'EN'=>'Chiayi County',
        'stations'=>[
            [
                'code'=>'4050',
                'TW'=>'大林',
                'EN'=>'Dalin',
            ],
            [
                'code'=>'4060',
                'TW'=>'民雄',
                'EN'=>'Minsyong',
            ],
            [
                'code'=>'4090',
                'TW'=>'水上',
                'EN'=>'Shueishang',
            ],
            [
                'code'=>'4100',
                'TW'=>'南靖',
                'EN'=>'Nanjing',
            ],
        ],
    ],
    'TainanCity'=>[
        'TW'=>'台南市',
        'EN'=>'Tainan City',
        'stations'=>[
            [
                'code'=>'4110',
                'TW'=>'後壁',
                'EN'=>'Houbi',
            ],
            [
                'code'=>'4120',
                'TW'=>'新營',
                'EN'=>'Sinying',
            ],
            [
                'code'=>'4130',
                'TW'=>'柳營',
                'EN'=>'Liouying',
            ],
            [
                'code'=>'4140',
                'TW'=>'林鳳營',
                'EN'=>'Linfongying',
            ],
            [
                'code'=>'4150',
                'TW'=>'隆田',
                'EN'=>'Longtian',
            ],
            [
                'code'=>'4160',
                'TW'=>'拔林',
                'EN'=>'Balin',
            ],
            [
                'code'=>'4170',
                'TW'=>'善化',
                'EN'=>'Shanhua',
            ],
            [
                'code'=>'4180',
                'TW'=>'南科',
                'EN'=>'Nanke',
            ],
            [
                'code'=>'4190',
                'TW'=>'新市',
                'EN'=>'Sinshih',
            ],
            [
                'code'=>'4200',
                'TW'=>'永康',
                'EN'=>'Yongkang',
            ],
            [
                'code'=>'4210',
                'TW'=>'大橋',
                'EN'=>'Daciao',
            ],
            [
                'code'=>'4220',
                'TW'=>'臺南',
                'EN'=>'Tainan',
            ],
            [
                'code'=>'4230',
                'TW'=>'林森',
                'EN'=>'Linsen',
            ],
            [
                'code'=>'4240',
                'TW'=>'南臺南',
                'EN'=>'South Tainan',
            ],
            [
                'code'=>'4250',
                'TW'=>'保安',
                'EN'=>'Baoan',
            ],
            [
                'code'=>'4260',
                'TW'=>'仁德',
                'EN'=>'Rende',
            ],
            [
                'code'=>'4270',
                'TW'=>'中洲',
                'EN'=>'Jhongjhou',
            ],
            [
                'code'=>'4271',
                'TW'=>'長榮大學',
                'EN'=>'Chang Jung Christian University',
            ],
            [
                'code'=>'4272',
                'TW'=>'沙崙',
                'EN'=>'Shalun',
            ],
        ],
    ],
    'KaohsiungCity'=>[
        'TW'=>'高雄市',
        'EN'=>'Kaohsiung City',
        'stations'=>[
            [
                'code'=>'4290',
                'TW'=>'大湖',
                'EN'=>'Dahu',
            ],
            [
                'code'=>'4300',
                'TW'=>'路竹',
                'EN'=>'Lujhu',
            ],
            [
                'code'=>'4310',
                'TW'=>'岡山',
                'EN'=>'Gangshan',
            ],
            [
                'code'=>'4320',
                'TW'=>'橋頭',
                'EN'=>'Ciaotou',
            ],
            [
                'code'=>'4330',
                'TW'=>'楠梓',
                'EN'=>'Nanzih',
            ],
            [
                'code'=>'4340',
                'TW'=>'新左營',
                'EN'=>'Xinzuoying',
            ],
            [
                'code'=>'4350',
                'TW'=>'左營',
                'EN'=>'Zuoying',
            ],
            [
                'code'=>'4360',
                'TW'=>'內惟',
                'EN'=>'Neiwei',
            ],
            [
                'code'=>'4370',
                'TW'=>'美術館',
                'EN'=>'Museum of Fine Arts',
            ],
            [
                'code'=>'4380',
                'TW'=>'鼓山',
                'EN'=>'Gushan',
            ],
            [
                'code'=>'4390',
                'TW'=>'三塊厝',
                'EN'=>'Sankuaicuo',
            ],
            [
                'code'=>'4400',
                'TW'=>'高雄',
                'EN'=>'Kaohsiung',
            ],
            [
                'code'=>'4410',
                'TW'=>'民族',
                'EN'=>'Minzu',
            ],
            [
                'code'=>'4420',
                'TW'=>'科工館',
                'EN'=>'Science And Technology Museum',
            ],
            [
                'code'=>'4430',
                'TW'=>'正義',
                'EN'=>'Zhengyi',
            ],
            [
                'code'=>'4440',
                'TW'=>'鳳山',
                'EN'=>'Fongshan',
            ],
            [
                'code'=>'4450',
                'TW'=>'後庄',
                'EN'=>'Houjhuang',
            ],
            [
                'code'=>'446',
                'TW'=>'九曲堂',
                'EN'=>'Jioucyutang',
            ],
        ],
    ],
    'PingtungCounty'=>[
        'TW'=>'屏東縣',
        'EN'=>'Pingtung County',
        'stations'=>[
            [
                'code'=>'4470',
                'TW'=>'六塊厝',
                'EN'=>'Lioukuaicuo',
            ],
            [
                'code'=>'5000',
                'TW'=>'屏東',
                'EN'=>'Pingtung',
            ],
            [
                'code'=>'5010',
                'TW'=>'歸來',
                'EN'=>'Gueilai',
            ],
            [
                'code'=>'5020',
                'TW'=>'麟洛',
                'EN'=>'Linluo',
            ],
            [
                'code'=>'5030',
                'TW'=>'西勢',
                'EN'=>'Sishih',
            ],
            [
                'code'=>'5040',
                'TW'=>'竹田',
                'EN'=>'Jhutian',
            ],
            [
                'code'=>'5050',
                'TW'=>'潮州',
                'EN'=>'Chaojhou',
            ],
            [
                'code'=>'5060',
                'TW'=>'崁頂',
                'EN'=>'Kanding',
            ],
            [
                'code'=>'5070',
                'TW'=>'南州',
                'EN'=>'Nanjhou',
            ],
            [
                'code'=>'5080',
                'TW'=>'鎮安',
                'EN'=>'Jhenan',
            ],
            [
                'code'=>'5090',
                'TW'=>'林邊',
                'EN'=>'Linbian',
            ],
            [
                'code'=>'5100',
                'TW'=>'佳冬',
                'EN'=>'Jiadong',
            ],
            [
                'code'=>'5110',
                'TW'=>'東海',
                'EN'=>'Donghai',
            ],
            [
                'code'=>'5120',
                'TW'=>'枋寮',
                'EN'=>'Fangliao',
            ],
            [
                'code'=>'5130',
                'TW'=>'加祿',
                'EN'=>'Jialu',
            ],
            [
                'code'=>'5140',
                'TW'=>'內獅',
                'EN'=>'Neishih',
            ],
            [
                'code'=>'516',
                'TW'=>'枋山',
                'EN'=>'Fangshan',
            ],

        ],
    ],
    'TaitungCounty'=>[
        'TW'=>'台東縣',
        'EN'=>'Taitung County',
        'stations'=>[
            [
                'code'=>'6070',
                'TW'=>'池上',
                'EN'=>'Chihshang',
            ],
            [
                'code'=>'6060',
                'TW'=>'海端',
                'EN'=>'Haiduan',
            ],
            [
                'code'=>'6050',
                'TW'=>'關山',
                'EN'=>'Guanshan',
            ],
            [
                'code'=>'6040',
                'TW'=>'瑞和',
                'EN'=>'Rueihe',
            ],
            [
                'code'=>'6030',
                'TW'=>'瑞源',
                'EN'=>'Rueiyuan',
            ],
            [
                'code'=>'6020',
                'TW'=>'鹿野',
                'EN'=>'Luye',
            ],
            [
                'code'=>'6010',
                'TW'=>'山里',
                'EN'=>'Shanli',
            ],
            [
                'code'=>'6000',
                'TW'=>'臺東',
                'EN'=>'Taitung',
            ],
            [
                'code'=>'5190',
                'TW'=>'大武',
                'EN'=>'Dawu',
            ],
            [
                'code'=>'5200',
                'TW'=>'瀧溪',
                'EN'=>'Lunghsi',
            ],
            [
                'code'=>'5210',
                'TW'=>'金崙',
                'EN'=>'Jinlun',
            ],
            [
                'code'=>'5220',
                'TW'=>'太麻里',
                'EN'=>'Taimali',
            ],
            [
                'code'=>'5230',
                'TW'=>'知本',
                'EN'=>'Jhihben',
            ],
            [
                'code'=>'5240',
                'TW'=>'康樂',
                'EN'=>'Kangle',
            ],
        ],
    ],
    'HualienCounty'=>[
        'TW'=>'花蓮縣',
        'EN'=>'Hualien County',
        'stations'=>[
            [
                'code'=>'7060',
                'TW'=>'和平',
                'EN'=>'Heping',
            ],
            [
                'code'=>'7050',
                'TW'=>'和仁',
                'EN'=>'Horen',
            ],
            [
                'code'=>'7040',
                'TW'=>'崇德',
                'EN'=>'Chongde',
            ],
            [
                'code'=>'7030',
                'TW'=>'新城',
                'EN'=>'Sincheng',
            ],
            [
                'code'=>'7020',
                'TW'=>'景美',
                'EN'=>'Jingmei',
            ],
            [
                'code'=>'7010',
                'TW'=>'北埔',
                'EN'=>'Beipu',
            ],
            [
                'code'=>'7000',
                'TW'=>'花蓮',
                'EN'=>'Hualien',
            ],
            [
                'code'=>'6250',
                'TW'=>'吉安',
                'EN'=>'Jian',
            ],
            [
                'code'=>'6240',
                'TW'=>'志學',
                'EN'=>'Jhihsyue',
            ],
            [
                'code'=>'6230',
                'TW'=>'平和',
                'EN'=>'Pinghe',
            ],
            [
                'code'=>'6220',
                'TW'=>'壽豐',
                'EN'=>'Shoufong',
            ],
            [
                'code'=>'6210',
                'TW'=>'豐田',
                'EN'=>'Fongtian',
            ],
            [
                'code'=>'6200',
                'TW'=>'林榮新光',
                'EN'=>'Linrong Shin Kong',
            ],
            [
                'code'=>'6190',
                'TW'=>'南平',
                'EN'=>'Nanping',
            ],
            [
                'code'=>'6180',
                'TW'=>'鳳林',
                'EN'=>'Fonglin',
            ],
            [
                'code'=>'6170',
                'TW'=>'萬榮',
                'EN'=>'Wanrong',
            ],
            [
                'code'=>'6160',
                'TW'=>'光復',
                'EN'=>'Guangfu',
            ],
            [
                'code'=>'6150',
                'TW'=>'大富',
                'EN'=>'Dafu',
            ],
            [
                'code'=>'6140',
                'TW'=>'富源',
                'EN'=>'Fuyuan',
            ],
            [
                'code'=>'6130',
                'TW'=>'瑞穗',
                'EN'=>'Rueisuei',
            ],
            [
                'code'=>'6120',
                'TW'=>'三民',
                'EN'=>'Sanmin',
            ],
            [
                'code'=>'6110',
                'TW'=>'玉里',
                'EN'=>'Yuli',
            ],
            [
                'code'=>'6100',
                'TW'=>'東里',
                'EN'=>'Dongli',
            ],
            [
                'code'=>'6090',
                'TW'=>'東竹',
                'EN'=>'Dongjhu',
            ],
            [
                'code'=>'6080',
                'TW'=>'富里',
                'EN'=>'Fuli',
            ],
        ],
    ],
    'YilanCounty'=>[
        'TW'=>'宜蘭縣',
        'EN'=>'Yilan County',
        'stations'=>[
            [
                'code'=>'7280',
                'TW'=>'石城',
                'EN'=>'Shihcheng',
            ],
            [
                'code'=>'7270',
                'TW'=>'大里',
                'EN'=>'Dali',
            ],
            [
                'code'=>'7260',
                'TW'=>'大溪',
                'EN'=>'Dasi',
            ],
            [
                'code'=>'7250',
                'TW'=>'龜山',
                'EN'=>'Gueishan',
            ],
            [
                'code'=>'7240',
                'TW'=>'外澳',
                'EN'=>'Waiao',
            ],
            [
                'code'=>'7230',
                'TW'=>'頭城',
                'EN'=>'Toucheng',
            ],
            [
                'code'=>'7220',
                'TW'=>'頂埔',
                'EN'=>'Dingpu',
            ],
            [
                'code'=>'7210',
                'TW'=>'礁溪',
                'EN'=>'Jiaohsi',
            ],
            [
                'code'=>'7200',
                'TW'=>'四城',
                'EN'=>'Sihcheng',
            ],
            [
                'code'=>'7190',
                'TW'=>'宜蘭',
                'EN'=>'Yilan',
            ],
            [
                'code'=>'7180',
                'TW'=>'二結',
                'EN'=>'Erjie',
            ],
            [
                'code'=>'7170',
                'TW'=>'中里',
                'EN'=>'Jhongli',
            ],
            [
                'code'=>'7160',
                'TW'=>'羅東',
                'EN'=>'Luodong',
            ],
            [
                'code'=>'7150',
                'TW'=>'冬山',
                'EN'=>'Dongshan',
            ],
            [
                'code'=>'7140',
                'TW'=>'新馬',
                'EN'=>'Sinma',
            ],
            [
                'code'=>'7130',
                'TW'=>'蘇澳新站',
                'EN'=>'Suaosin',
            ],
            [
                'code'=>'7120',
                'TW'=>'蘇澳',
                'EN'=>'Suao',
            ],
            [
                'code'=>'7110',
                'TW'=>'永樂',
                'EN'=>'Yongle',
            ],
            [
                'code'=>'7100',
                'TW'=>'東澳',
                'EN'=>'Dongao',
            ],
            [
                'code'=>'7090',
                'TW'=>'南澳',
                'EN'=>'Nanao',
            ],
            [
                'code'=>'7080',
                'TW'=>'武塔',
                'EN'=>'Wuta',
            ],
            [
                'code'=>'7070',
                'TW'=>'漢本',
                'EN'=>'Hanben',
            ],
        ],
    ],
];